# This workflow will test the BobbysNews app.

name: Swift

on: [push]

jobs:
  build:
    runs-on: macos-15
    strategy:
      fail-fast: false
      matrix:
        name: ['iPhone 16 Pro', 'iPad Pro 13-inch (M4)']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Xcode
        run: |
        XCODE_ROOT=/Applications/Xcode_26.0.app
        echo "MD_APPLE_SDK_ROOT=$XCODE_ROOT" >> $GITHUB_ENV
        sudo xcode-select -s $XCODE_ROOT
      - name: Run SwiftFormat
        run: swiftformat --lint . --reporter github-actions-log --swiftversion 6.2
      - name: Run tests
        run: set -o pipefail && xcodebuild clean test -project BobbysNews.xcodeproj -scheme BobbysNews -destination 'platform=iOS Simulator,name=${{ matrix.name }},OS=latest' | xcbeautify --renderer github-actions
