# This workflow will test the BobbysNews app.

name: Swift

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  swift_format:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - name: Run SwiftFormat
        run: swiftformat --lint . --reporter github-actions-log --swiftversion 6.0

  iPhone_test:
    needs: swift_format
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - name: Install xcpretty
        run: gem install xcpretty
      - name: Run tests (iPhone 16 Pro)
        run: xcodebuild -project BobbysNews.xcodeproj -scheme BobbysNews -destination 'platform=iOS Simulator,name=iPhone 16 Pro' clean test | xcpretty

  iPad_test:
    needs: swift_format
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - name: Install xcpretty
        run: gem install xcpretty
      - name: Run tests (iPad Pro 13-inch (M4))
        run: xcodebuild -project BobbysNews.xcodeproj -scheme BobbysNews -destination 'platform=iOS Simulator,name=iPad Pro 13-inch (M4)' clean test | xcpretty
