# This workflow will test the BobbysNews app.

name: Swift

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest
      - name: Set up Swift
        uses: swift-actions/setup-swift@v2
      - name: Run SwiftFormat
        run: swiftformat --lint . --reporter github-actions-log --swiftversion 6.0

  test_iPhone:
    needs: setup
    steps:
      - name: iPhone 16 Pro
        run: xcodebuild test -scheme BobbysNews -project BobbysNews.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 16 Pro' | xcbeautify && exit ${PIPESTATUS[0]}

  test_iPad:
    needs: setup
    steps:
      - name: iPad Pro 13-inch (M4)
        run: xcodebuild test -scheme BobbysNews -project BobbysNews.xcodeproj -destination 'platform=iOS Simulator,name=iPad Pro 13-inch (M4)' | xcbeautify && exit ${PIPESTATUS[0]}
